version: '3.4'

networks:
   frontend:
   backend:



services:
    orderprocessorapi:
       build:
          context: .\OrderProcessorAPI
          dockerfile: Dockerfile
       image: orderprocessorapi
       environment:
          DatabaseServer: mssqlserver
          DatabaseName: OrderDb
          DatabaseUser: sa
          DatabaseUserPassword: ProductApi(!)
       container_name: orderapi
       ports:
          - "5000:80"
       networks:
          - backend
          - frontend
       depends_on:
          - mssqlserver

    mssqlserver:
       image: "microsoft/mssql-server-linux:latest"
       ports:
          - "1445:1433"

       container_name: mssqlcontainer
       environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: ProductApi(!)
       networks:
          - backend