version: '3.4'

services:
  eventmanagementapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  orderprocessorapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  eventcatalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  searcheventapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ticketsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat




