version: '3.4'

services:
  eventmanagementapi:
    image: ${DOCKER_REGISTRY}eventmanagementapi
    build:
      context: .
      dockerfile: EventManagementAPI\Dockerfile


  orderprocessorapi:
    image: ${DOCKER_REGISTRY}orderprocessorapi
    build:
      context: .
      dockerfile: OrderProcessorAPI\Dockerfile


  eventcatalogapi:
    image: ${DOCKER_REGISTRY}eventcatalogapi
    build:
      context: .
      dockerfile: EventCatalogAPI\Dockerfile


  searcheventapi:
    image: ${DOCKER_REGISTRY}searcheventapi
    build:
      context: .
      dockerfile: SearchEventAPI/Dockerfile


  ticketsapi:
    image: ${DOCKER_REGISTRY}ticketsapi
    build:
      context: .
      dockerfile: TicketsAPI/Dockerfile



  webmvcclient:
    image: ${DOCKER_REGISTRY}webmvcclient
    build:
      context: .
      dockerfile: ../WebMvcClient/Dockerfile
      
  tokenserviceapi:
    image: ${DOCKER_REGISTRY}tokenserviceapi
    build:
      context: .
      dockerfile: TokenServiceAPI/Dockerfile


