version: '3.4'

networks:

   frontend:

   backend:



services:

   webmvcclient:
      build:
         context: ..\WebMvcClient
         dockerfile: Dockerfile
      environment:
         ASPNETCORE_ENVIRONMENT: Development
         OrderUrl: http://order
      container_name: webshop
      ports:
         - "5200:80"
      networks:
         - frontend
      depends_on:
         - order

   order:
      build:
         context: .\OrderProcessorAPI
         dockerfile: Dockerfile
      image: orderapi
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: OrderDb
         DatabaseUser: sa
         DatabaseUserPassword: ProductApi(!)
      container_name: orderprocessorapi1
      ports:
         - "5000:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1445:1433"
      container_name: mssqlcontainer
      environment:
         ACCEPT_EULA: Y
         SA_PASSWORD: ProductApi(!)
      networks:
         - backend